### ISSUE TITLE
Why does picker.on("change", ...) fire on page load?

### ISSUE THREAD

**Issue by jjrabbit** [tovic/color-picker#46]
Anyone know why `picker.on("change", function(color) {...});` fires on page load?

Ideally I would like to only have it fire if the color picker is interacted with but for some reason it fires even if I never use the color picker.

Basic example:

``` .html
<script>

    var source = document.querySelector('input'),
        picker = new CP(source);

    // prevent showing native color picker panel
    source.onclick = function(e) {
        e.preventDefault();
    };

    picker.on("change", function(color) {
        alert('fire');
        this.source.value = '#' + color;
    });

</script>
```

**Comment by tovic** [comment]
That was used to make sure that a color value defined in the input element will update the &ldquo;any&rdquo; elements you want to change the color based on that input value.

Try the `drag` event maybe?

**Comment by tovic** [comment]
Alternative would be something like this:

~~~ .js
var changed;
picker.on("change", function(color) {
    if (changed) {
        alert('fire');
    } else {
        changed = true;
    }
    this.source.value = '#' + color;
});
~~~

**Comment by jjrabbit** [comment]
Oops I completely missed the documentation on the hooks. I'll be sure to read more thoroughly before posting an issue next time!

The `drag` event is closer to what I was looking for but actually `start` + `drag` (for example `picker.on("start drag", function(color) {...})` is the type of listening I was trying to achieve. Would be cool if you could combine them in a single statement like that but that's not a big deal.

Your alternative is genius and works great. I'll just do it that way.

Thanks tovic!

**Comment by jjrabbit** [comment]
Alternative idea: maybe there could be a new hook/event called `pick` which combines the functionality of `start` and `drag`.

For example:
```javascript
picker.on("pick", function(color) {
    this.source.value = '#' + color;
});
```

This way the event only fires when someone chooses a color, which in the end is what I think most people are trying to listen for.

Regardless the plugin already works great!

**Comment by tovic** [comment]
I would recommend you to use a wrapper because each suggestion made by users has potential to complicate the existing features. I&rsquo;m afraid that this color picker widget won&rsquo;t be called &ldquo;simple&rdquo; anymore in the future just because of my generosity in accepting feature requests.

Basically, you can make an empty hook that you can trigger with `fire` method. So that, in your case it can be made like this:

~~~ .js
// The Wrapper
CP.each(function() {
  this.changed = false;
  this.on("change", function(color) {
    if (this.changed) {
      this.fire("pick", [color]);
    } else {
      this.changed = true;
    }
  });
});

// Yours
var picker = new CP(document.querySelector('input'));
picker.on("pick", function(color) {
  this.source.value = '#' + color;
  document.body.style.backgroundColor = '#' + color;
})
~~~

**Demo:** https://jsfiddle.net/9xo0bksf

**Comment by jjrabbit** [comment]
Simple is definitely better, it was just an idea.

If it complicates things no sense implementing it.

Thanks!
